### ISSUE TITLE
Neglect "disabled" KPI score

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/MCMSMV#3]
The "not applicable" KPI scores still show up in the MCMSMV module. They have the attribute "disabled": true. Can we use this attribute to neglect these scores in the MCMSMV overview?

![image](https://cloud.githubusercontent.com/assets/12395999/8179900/4d78ea4e-141a-11e5-8609-d742b4431395.png)

**Comment by WimPlokker** [comment]
Implemented in Stockholm version
