### ISSUE TITLE
Show entire KPI name

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/MCMSMV#4]
Part of the KPI name is cut off in the MCMSMV interface. This makes KPI's (e.g. Gas_use_m3_year_dwelling_Havensteder and Gas_use_m3_year_dwelling_HugodeGroot) indistinguishable.

![image](https://cloud.githubusercontent.com/assets/12395999/8277151/f1a9bfd6-18bf-11e5-912d-205e4a749c26.png)

**Comment by WimPlokker** [comment]
Implemented in Warsaw version
